### ISSUE TITLE
activeLeagueFixtures is undefined

### ISSUE THREAD

**Issue by ghost** [master117/MagicMirror-FootballLeagues#1]
Hello
I've just installed your module, but it does not work, with or without apikey 

here is my config file
{
                        module: 'MagicMirror-FootballLeagues',
                        position: 'top_right',
                        header: 'Football Adrien',
                        config:  {
                                        leagues: [450],
                                        showNames: true,
                                        displayTime: 60 * 1000 * 2,
                                        showTables: true,
                                        apiKey: 'xxxxxxx'
                        }
                },

**Comment by master117** [comment]
Hello,

that is sad to hear.

I just installed MagicMirror from Scratch, pulled this repo and used the config you provided. And it works for me. 
https://i.imgur.com/0KYmCEN.png

1. You wrote: activeLeagueFixtures is undefined as the title, 

could you give me more information on that? Where does that error appear, in the console, in browser? Does it repeat? Is there line numbers? activeLeagueFixtures are the fixtures of the selected league and should not be undefined at any moment.

2. I added a bit more additional error logging to the code, so it would be great if you could update.

3. I assume all the files from the repo are where they should be?

Greetings,
Johannes

**Comment by master117** [comment]
I think I have found the bug and fixed it, it was a racing condition. Please update to the newest version and reopen this issue if the problem still exists.

**Comment by ghost** [comment]
Thanks for your time , now it's working fine.
Maybe because my ISP speed sucks, I often run into hidden bugs :)
Anyway have a good week end !

**Comment by master117** [comment]
Glad this fixed your issue. Please let me know if you encounter any other bugs.
