### ISSUE TITLE
Not updating scores regularly

### ISSUE THREAD

**Issue by simphide** [master117/MagicMirror-FootballLeagues#10]
Hi.

I currently have the problem that the module does not update the scores regularly. I need to restart MagicMirror to get the latest scores. Does anyone else have the same problem or a solution?

Many thanks in advance!

**Comment by xKrummy** [comment]
as mentioned in the description: All Data is from: football-data.org

> Sadly football-data.org has introduced Tiers and Pricing which means:
> - You need a key from their site to use this tool. A free API key can be aquired here.
> - There is only a few leagues available, only 10 updates per minute and delayed scores (not live) in the free version.

Basicall with the key there are still only 50 max daily updates allowed. But this is by far not enough for live ticker. The module basically only asks current status only every  few minutes (ltes assume 30 minutes max). But if you restart the mirror you force it to send a new request each time. Thats why rebooting "temporarly" helps

**Comment by master117** [comment]
When we switched to football-data.org they offered way more daily updates, but sadly they keep killing their free api to force users in the paid one.
