### ISSUE TITLE
Error displayed

### ISSUE THREAD

**Issue by HanaO00** [master117/MagicMirror-FootballLeagues#14]
Hello, i have this error in the magic mirror log
![Screenshot-2021-08-30_00-05-17](https://user-images.githubusercontent.com/17810985/131266820-5dbb2ccf-1596-42cb-abbc-f214edc83f1e.png)

**Comment by master117** [comment]
Hi, sorry I forgot to update the documentation after a recent update. You need to install the fetch package:

https://www.npmjs.com/package/node-fetch

You can do this by entering:

`npm install node-fetch`

Documentation has been updated.

**Comment by HanaO00** [comment]
Oh thank you ! I close the issue

**Comment by HanaO00** [comment]
Edit: I have successfully installed node-fetch but the error persists.

**Comment by master117** [comment]
Hi, I just checked and you are correct. I just uploaded a fixed version that works locally. Sorry for the issues, hope it works for you now.

**Comment by HanaO00** [comment]
Everything works perfectly, thank you
