### ISSUE TITLE
World Cup 2018 Russia not working

### ISSUE THREAD

**Issue by ghost** [master117/MagicMirror-FootballLeagues#5]
Hello, 

It's seems that the ID : 467 is not displaying any information, could you confirm this ?

as described here https://www.football-data.org/
it should be there
World Cup API Endpoint: http://api.football-data.org/v1/competitions/467 

thanks.

**Comment by master117** [comment]
Thanks for bringing this to my attention. Apparently some cups have a different format in the API. I added support for this. 
I added the variable: showUnavailable to show Leagues that are currently not available, which includes the world cup at this point, so you must add showUnavailable: true to your config.

**Comment by ghost** [comment]
Working fine, thanks for your time and reactivity 🥇
