### ISSUE TITLE
Can change de size of the module?

### ISSUE THREAD

**Issue by Neoderek** [master117/MagicMirror-FootballLeagues#6]
I look the readme, but is blank :S 
in the .css only therer are code for magins of the module and i cant re-size the module for a small height.

Thanks so much

**Comment by master117** [comment]
Readme.md contains the same info as the Frontpage of this repo: https://github.com/master117/MagicMirror-FootballLeagues

There is currently no implementation to change the height. But you can make one yourself! Things you need to change:

Font-Size
Image height of the logos

Both can be done through css. Let me know if you need more help.

Cheers,
