### ISSUE TITLE
world cup fixtures tuncated

### ISSUE THREAD

**Issue by ghost** [master117/MagicMirror-FootballLeagues#7]
Hello, 

I don't know what is happening but the fixtures table for the World Cup is truncated and stop rolling with the current day (displaying only from june 14th to 19th)

https://framapic.org/cpajvAO5x3jX/40sAveFozVvV.jpg

data are presents when calling the api
http://api.football-data.org/v1/competitions/467/fixtures

**Comment by master117** [comment]
Fixtures where not scrolling as they should. This will be fixed when another long tournament arrives. FootballData recently changed their API and there is now a better way to handle this Problem. Inactive for now.
