### ISSUE TITLE
v2 api

### ISSUE THREAD

**Issue by ghost** [master117/MagicMirror-FootballLeagues#8]
Hello

Do you have any plan to update your module to support the v2 api from daniel ?
As i can see the v1 is still working but no more score update.

Thanks.

**Comment by master117** [comment]
Currently on a longer trip abroad, I will look into it in 3 weeks. Sorry for the delay. If you have any coding knowledge feel free to make a pull request.

**Comment by ruffneck2** [comment]
Hi,

> I will look into it in 3 weeks.

Do you have an update or schedule when v2 api will be supported?
I'm waiting for it eagerly, but unfortunately by myself have no further coding knowledge to take action.

**Comment by ghost** [comment]
Me too, I would be able to fix small thing, but here we are talking about upgrading from v1 api to v2 .. I'm not able to do it .. I hope @master117 will find the time and the motivation to do it 👍

**Comment by master117** [comment]
@prysme01 @ruffneck2 I just updated the Programm to use the V2 api. Sorry it took so long, trip abroad took a bit longer than expected.

V2 comes with a few changes, sadly, so make sure to read the updated Readme.

**Comment by ghost** [comment]
Great thank you very much for your work, my son will be happy to catch up with the scores 🥇
